import blue from "../assets/vinyl-blue.jpeg";
import black from "../assets/vinyl-black.jpeg";
import red from "../assets/vinyl-red.jpeg";
import yellow from "../assets/vinyl-yellow.jpeg";
import purple from "../assets/vinyl-purple.jpeg";
import green from "../assets/vinyl-green.jpeg";

export const vinylList = [
  {
    name: "33 tours",
    size: "12 pouces",
    duration: "30 minutes",
    color: "blue",
    id: "1ed",
    isBestSale: true,
    sensitivity: 3,
    durability: 3,
    cover: blue,
    price: 25,
  },
  {
    name: "Maxi 45 tours",
    size: "10 pouces",
    duration: "20 minutes",
    color: "blue",
    id: "2ab",
    sensitivity: 3,
    durability: 2,
    cover: blue,
    price: 23,
  },
  {
    name: "45 tours",
    size: "7 pouces",
    duration: "10 minutes",
    color: "blue",
    id: "3sd",
    sensitivity: 2,
    durability: 1,
    cover: blue,
    price: 21,
  },
  {
    name: "33 tours",
    size: "12 pouces",
    duration: "30 minutes",
    color: "yellow",
    id: "1cd",
    isSpecialOffer: true,
    sensitivity: 3,
    durability: 1,
    cover: yellow,
    price: 24,
  },
  {
    name: "Maxi 45 tours",
    size: "10 pouces",
    duration: "20 minutes",
    color: "yellow",
    id: "2ac",
    sensitivity: 2,
    durability: 2,
    cover: yellow,
    price: 22,
  },
  {
    name: "45 tours",
    size: "7 pouces",
    duration: "10 minutes",
    color: "yellow",
    id: "3se",
    sensitivity: 2,
    durability: 1,
    cover: yellow,
    price: 20,
  },
  {
    name: "33 tours",
    size: "12 pouces",
    duration: "30 minutes",
    color: "black",
    id: "1fd",
    isBestSale: true,
    sensitivity: 3,
    durability: 3,
    cover: black,
    price: 20,
  },
  {
    name: "Maxi 45 tours",
    size: "10 pouces",
    duration: "20 minutes",
    color: "black",
    id: "2bb",
    sensitivity: 3,
    durability: 2,
    cover: black,
    price: 18,
  },
  {
    name: "45 tours",
    size: "7 pouces",
    duration: "10 minutes",
    color: "black",
    id: "3td",
    sensitivity: 2,
    durability: 3,
    cover: black,
    price: 16,
  },
  {
    name: "33 tours",
    size: "12 pouces",
    duration: "30 minutes",
    color: "green",
    id: "1dd",
    isSpecialOffer: true,
    sensitivity: 2,
    durability: 3,
    cover: green,
    price: 22,
  },
  {
    name: "Maxi 45 tours",
    size: "10 pouces",
    duration: "20 minutes",
    color: "green",
    id: "2zb",
    sensitivity: 2,
    durability: 2,
    cover: green,
    price: 20,
  },
  {
    name: "45 tours",
    size: "7 pouces",
    duration: "10 minutes",
    color: "green",
    id: "3rd",
    sensitivity: 1,
    durability: 1,
    cover: green,
    price: 18,
  },
  {
    name: "33 tours",
    size: "12 pouces",
    duration: "30 minutes",
    color: "red",
    id: "1dc",
    isSpecialOffer: true,
    sensitivity: 2,
    durability: 1,
    cover: red,
    price: 26,
  },
  {
    name: "Maxi 45 tours",
    size: "10 pouces",
    duration: "20 minutes",
    color: "red",
    id: "2za",
    isBestSale: true,
    sensitivity: 2,
    durability: 2,
    cover: red,
    price: 24,
  },
  {
    name: "45 tours",
    size: "7 pouces",
    duration: "10 minutes",
    color: "red",
    id: "3rc",
    sensitivity: 3,
    durability: 1,
    cover: red,
    price: 22,
  },
  {
    name: "33 tours",
    size: "12 pouces",
    duration: "30 minutes",
    color: "purple",
    id: "1cc",
    isBestSale: true,
    sensitivity: 3,
    durability: 3,
    cover: purple,
    price: 28,
  },
  {
    name: "Maxi 45 tours",
    size: "10 pouces",
    duration: "20 minutes",
    color: "purple",
    id: "2yz",
    sensitivity: 3,
    durability: 3,
    cover: purple,
    price: 26,
  },
  {
    name: "45 tours",
    size: "7 pouces",
    duration: "10 minutes",
    color: "purple",
    id: "3qd",
    sensitivity: 3,
    durability: 3,
    cover: purple,
    price: 24,
  },
];
